### ISSUE TITLE
PrerollUpdate.py fails with Python 3.10

### ISSUE THREAD

**Issue by lishremix** [TheHumanRobot/Rollarr#11]
Thank you for this update! I'm just getting everything setup. When I run the GUI I am able to update the Plex Preroll field without issue. However, when I'm calling Prerollupdate.py through a Windows scheduled task, nothing happens. I ran Prerollupdate.py manually through cmd and I get the following error. Is this not compatible with Python 3.10?

```
C:\Rollarr\dist\dist\Preroll>prerollupdate.py
Traceback (most recent call last):
  File "C:\Rollarr\dist\dist\Preroll\PrerollUpdate.py", line 2, in <module>
    import PySimpleGUI as sg
  File "C:\Users\kyled\AppData\Local\Programs\Python\Python310\lib\site-packages\PySimpleGUI\__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "C:\Users\kyled\AppData\Local\Programs\Python\Python310\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 128, in <module>
    import tkinter as tk
  File "C:\Users\kyled\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: Module use of python37.dll conflicts with this version of Python.
```

**Comment by frankrende** [comment]
This is happening to me too. @TheHumanRobot can you take a look?

**Comment by frankrende** [comment]
Just to note, I've tried using Python 3.10, 3.9 and 3.7 - all of them have failed to update the pre-roll. I need to use the .exe in order for it to work (so my monthly job cannot be automated). A fix would be greatly appreciated!

**Comment by DanasaurUK** [comment]
I have tried this with Python 3.8 and it is still failing, renaming python37.dll to python37.old results in

```cmd
python PrerollUpdate.py
Traceback (most recent call last):
  File "PrerollUpdate.py", line 2, in <module>
    import PySimpleGUI as sg
  File "C:\Python38\lib\site-packages\PySimpleGUI\__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "C:\Python38\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 127, in <module>
    import tkinter as tk
  File "C:\Python38\lib\tkinter\__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: DLL load failed while importing _tkinter: The specified module could not be found.```

**Comment by mdonato9** [comment]
any update on what might fix this issue?

**Comment by frankrende** [comment]
Hi @mdonato9 -
I got it working months ago by making some changes to the PrerollUpdate.py file. I couldn't remember exactly what I changed, so here's some compare screenshots from the original file (left side) and my modified file (right side). Hopefully that works for you.
![image](https://user-images.githubusercontent.com/4317891/198325292-4d3e9d72-04ed-4f4e-916b-5472c328cbd2.png)
![image](https://user-images.githubusercontent.com/4317891/198325366-2224d910-17e1-4617-b98b-395393dc2153.png)

My PrerollBatchJob.bat file contains:
`"C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37\python.exe" "C:\Plex-Automatic-Preroll GUI\PrerollUpdate.py"
pause`
